[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/staff"
  to = "/staff.html"
  status = 200

[[redirects]]
  from = "/brag"
  to = "/brag-output/preview.html"
  status = 200
